zuul:
  semaphore:
    max-semaphores: 400
  routes:
    one:
      path: /auth/**
      serviceId: auth
      #url: http://localhost:8888/baoban/
    two:
      path: /core/**
      serviceId: core
  prefix: /zuuldmp
spring:
  application:
    name: zuuldmp
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
  ###############################---redis---##############################
  redis:
     host: ${REDIS_HOST:127.0.0.1}
     port: ${REDIS_PORT:6379}
     password: ${REDIS_PASSWORD:}
###############################---jwt---##############################
jwt:
  # 加密秘钥
  secret: f4e2e5203434xx1WET12^%3^(WE45
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
###############################---log---##############################
logging:
  file: ./logback.log
###############################---网关忽略校验的地址---##############################
gate:
  ignore:
    startWith: ${zuul.prefix}/about, ${zuul.prefix}/test
    contain: ., test, login, sms
zuulauth:
  duration:
    code-fetch: 10
ribbon:
  #Ribbon允许最大连接数，即所有后端微服务实例请求并发数之和的最大值。
  MaxTotalConnections: 400
  #单个后端微服务实例能接收的最大请求并发数  
  MaxConnectionsPerHost: 400
  ReadTimeout: 5000
  SocketTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          read:
            timeoutInMilliseconds: 5000
server:
  tomcat:
    max-threads: 400