zuul:
  routes:
    one:
      path: /auth/**
      serviceId: auth
      #url: http://localhost:8888/baoban/
    two:
      path: /core/**
      serviceId: core
  prefix: /zuuldmp
spring:
  application:
    name: zuuldmp
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
  ###############################---redis---##############################
  redis:
     host: ${REDIS_HOST:127.0.0.1}
     port: ${REDIS_PORT:6379}
     password: ${REDIS_PASSWORD:}
###############################---jwt---##############################
jwt:
  # 加密秘钥
  secret: f4e2e5203434xx1WET12^%3^(WE45
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
###############################---log---##############################
logging:
  file: ./logback.log
###############################---网关忽略校验的地址---##############################
gate:
  ignore:
    startWith: ${zuul.prefix}/about, ${zuul.prefix}/test
    contain: ., test, login, sms
zuulauth:
  duration:
    code-fetch: 10